//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbertoSazAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculos
    {
        public int id { get; set; }
        public string Matricula { get; set; }
        public string Color { get; set; }
        public Nullable<int> SerieId { get; set; }
    }
}
